theme: jekyll-theme-cayman
show_downloads: "false"

name: "Ankit Apurv's Blog"
title: "Ankit Apurv's Blog"
description: "Explore, Improve, Be Curious..."

url: "https://ankitapurv.github.io"

excerpt_separator: <!--end-excerpt-->

markdown: kramdown

kramdown:
    input: GFM

exclude: ["README.md"]
